spring:
  application:
    name: backend-donation
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  profiles:
    include: secret


server:
  port: 8085

logging:
  level:
    com:
      cg:
        farmirang: debug
