apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort
  selector:
    app: spring-boot-load
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-farm
  namespace: farmirang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-farm
  template:
    metadata:
      labels:
        app: app-farm
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: container-farm
          image: docker.io/hyeonjongkim/farm:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          env:
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 8080