apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  namespace: farmirang
spec:
  type: NodePort
  selector:
    app: farm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000