import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <div className="sticky top-0">
          <NavBar />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
