import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Navbar";
import ChatButton from "./chatButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body>
        <div className="flex flex-col h-full">
          <NavBar />
          {children}
          <ChatButton />
        </div>
      </body>
    </html>
  );
}
