apiVersion: v1
kind: Service
metadata:
  name: app-agency-service
  namespace: farmirang
spec:
  selector:
    app: app-agency
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
