apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-design-deployment
  namespace: farmirang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-design
  template:
    metadata:
      labels:
        app: app-design
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: container-design
          image: docker.io/hyeonjongkim/design:latest
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          env:
            - name: TZ
              value: Asia/Seoul
          ports:
            - containerPort: 8080
