apiVersion: v1
kind: Service
metadata:
  name: app-design-service
  namespace: farmirang
spec:
  selector:
    app: app-design
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
