spring:
  application:
    name: backend-user
  profiles:
    include: secret

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          redis: DEBUG


server:
  port: 8080